// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nosh.Data;

namespace Nosh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190506144926_NoshMigration")]
    partial class NoshMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Nosh.Models.Snack", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SnackTypeId");

                    b.Property<int>("snackCalories")
                        .HasMaxLength(4);

                    b.Property<string>("snackName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("snackPrice");

                    b.Property<int>("vendingMachineId");

                    b.HasKey("id");

                    b.HasIndex("SnackTypeId");

                    b.HasIndex("vendingMachineId");

                    b.ToTable("Snack");

                    b.HasData(
                        new
                        {
                            id = 1,
                            SnackTypeId = 3,
                            snackCalories = 210,
                            snackName = "Reese's Peanut Butter Cups",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 2,
                            SnackTypeId = 1,
                            snackCalories = 140,
                            snackName = "Coke",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 3,
                            SnackTypeId = 2,
                            snackCalories = 160,
                            snackName = "Lays Original",
                            snackPrice = 0.75,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 4,
                            SnackTypeId = 1,
                            snackCalories = 240,
                            snackName = "Iced Coffee",
                            snackPrice = 3.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 5,
                            SnackTypeId = 2,
                            snackCalories = 160,
                            snackName = "Lays BBQ",
                            snackPrice = 0.75,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 6,
                            SnackTypeId = 3,
                            snackCalories = 215,
                            snackName = "Snickers",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 7,
                            SnackTypeId = 1,
                            snackCalories = 150,
                            snackName = "Dr. Pepper",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 8,
                            SnackTypeId = 2,
                            snackCalories = 150,
                            snackName = "Doritos Salsa Verde",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 9,
                            SnackTypeId = 1,
                            snackCalories = 168,
                            snackName = "Red Bull",
                            snackPrice = 2.5,
                            vendingMachineId = 2
                        });
                });

            modelBuilder.Entity("Nosh.Models.SnackType", b =>
                {
                    b.Property<int>("SnackTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Snackid");

                    b.Property<string>("imageURL");

                    b.Property<string>("snackTypeName");

                    b.HasKey("SnackTypeId");

                    b.HasIndex("Snackid");

                    b.ToTable("SnackType");

                    b.HasData(
                        new
                        {
                            SnackTypeId = 1,
                            imageURL = "/images/milk-bottle.png",
                            snackTypeName = "Drink"
                        },
                        new
                        {
                            SnackTypeId = 2,
                            imageURL = "/images/snack.png",
                            snackTypeName = "Chip"
                        },
                        new
                        {
                            SnackTypeId = 3,
                            imageURL = "/images/chocolate-bar.png",
                            snackTypeName = "Candy"
                        });
                });

            modelBuilder.Entity("Nosh.Models.UserSnack", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("snackId");

                    b.Property<int>("userId");

                    b.Property<string>("userId1");

                    b.HasKey("id");

                    b.HasIndex("snackId");

                    b.HasIndex("userId1");

                    b.ToTable("UserSnack");

                    b.HasData(
                        new
                        {
                            id = 1,
                            snackId = 8,
                            userId = 1
                        },
                        new
                        {
                            id = 2,
                            snackId = 7,
                            userId = 1
                        },
                        new
                        {
                            id = 3,
                            snackId = 9,
                            userId = 2
                        },
                        new
                        {
                            id = 4,
                            snackId = 1,
                            userId = 3
                        },
                        new
                        {
                            id = 5,
                            snackId = 7,
                            userId = 3
                        });
                });

            modelBuilder.Entity("Nosh.Models.VendingMachine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("vendingMachineLocation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("vendingMachineName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("VendingMachine");

                    b.HasData(
                        new
                        {
                            id = 2,
                            vendingMachineLocation = "Closest to the coffee pot",
                            vendingMachineName = "Loud and Cold"
                        },
                        new
                        {
                            id = 1,
                            vendingMachineLocation = "Across from the microwaves",
                            vendingMachineName = "The Mothership"
                        });
                });

            modelBuilder.Entity("Nosh.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("firstName")
                        .IsRequired();

                    b.Property<bool>("isVendor");

                    b.Property<string>("lastName")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "44450521-c8ba-4a08-9700-0bb092c54d3f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c26790b9-c258-4551-a57d-e08908476922",
                            Email = "hmetts@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HMETTS@GMAIL.COM",
                            NormalizedUserName = "HMETTS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFYTc1UX6b2tPXKrJfWf6Ra5LRCXizf8FPhVV7Lt/U6xU3fEPrLbfGnAmUsfTrdw9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01f36f76-b5fe-4103-a319-a4b6adf0b2b5",
                            TwoFactorEnabled = false,
                            UserName = "hmetts@gmail.com",
                            firstName = "Hunter",
                            isVendor = false,
                            lastName = "Metts"
                        },
                        new
                        {
                            Id = "e17cdf4b-25c2-4a3f-8254-7f7227c8c317",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa251e76-16a7-466b-a489-ab7510bccb58",
                            Email = "jrosas@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JROSAS@GMAIL.COM",
                            NormalizedUserName = "JROSAS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGPBqeybWfdCxHZJWGlb09X1ZF9+VzQvGp66QmebOAlrUw+JilOjn6DRFbKNvm/CeA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b54cea3f-8604-43f5-9809-3dc6c69a990f",
                            TwoFactorEnabled = false,
                            UserName = "jrosas@gmail.com",
                            firstName = "Jordan",
                            isVendor = false,
                            lastName = "Rosas"
                        },
                        new
                        {
                            Id = "95a0e8fa-cd84-4f0b-9f2d-b02d16763df4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ffba7256-3ac9-4172-9bec-41b32da15c20",
                            Email = "acarter@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACARTER@GMAIL.COM",
                            NormalizedUserName = "ACARTER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKSZGdrcHytPKudzZbnYg03KtLTVcbUdxcuYmXySfx7YAoOsjsiXm0Zwve1bSwK+Fw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e74e2af-3d6b-4364-8210-1ae7c7bdad32",
                            TwoFactorEnabled = false,
                            UserName = "acarter@gmail.com",
                            firstName = "Asia",
                            isVendor = false,
                            lastName = "Carter"
                        },
                        new
                        {
                            Id = "c825360f-b2ae-4aee-8ec4-22a48e2bee9c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0b5b8d1-7c0d-4cac-bf8b-b8bb8fc47a21",
                            Email = "sbrader@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SBRADER@GMAIL.COM",
                            NormalizedUserName = "SBRADER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECzygvnfKnt3hReXHbiaQ/dmnCEncTQIOL+POja/sA54PX33+hO9DpKBQBZ4iug6Ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00cfe3ef-b473-45b3-b92e-c2f8c69ebbd6",
                            TwoFactorEnabled = false,
                            UserName = "sbrader@gmail.com",
                            firstName = "Steven",
                            isVendor = true,
                            lastName = "Brader"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Nosh.Models.Snack", b =>
                {
                    b.HasOne("Nosh.Models.SnackType", "snackType")
                        .WithMany()
                        .HasForeignKey("SnackTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nosh.Models.VendingMachine", "vendingMachine")
                        .WithMany("Snack")
                        .HasForeignKey("vendingMachineId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nosh.Models.SnackType", b =>
                {
                    b.HasOne("Nosh.Models.Snack")
                        .WithMany("SnackType")
                        .HasForeignKey("Snackid");
                });

            modelBuilder.Entity("Nosh.Models.UserSnack", b =>
                {
                    b.HasOne("Nosh.Models.Snack", "snack")
                        .WithMany("UserSnack")
                        .HasForeignKey("snackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nosh.Models.User", "user")
                        .WithMany("UserSnack")
                        .HasForeignKey("userId1");
                });
#pragma warning restore 612, 618
        }
    }
}
