// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nosh.Data;

namespace Nosh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190506183305_NoshMigration2")]
    partial class NoshMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Nosh.Models.Snack", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SnackTypeId");

                    b.Property<int>("snackCalories");

                    b.Property<string>("snackName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("snackPrice");

                    b.Property<int>("vendingMachineId");

                    b.HasKey("id");

                    b.HasIndex("SnackTypeId");

                    b.HasIndex("vendingMachineId");

                    b.ToTable("Snack");

                    b.HasData(
                        new
                        {
                            id = 1,
                            SnackTypeId = 3,
                            snackCalories = 210,
                            snackName = "Reese's Peanut Butter Cups",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 2,
                            SnackTypeId = 1,
                            snackCalories = 140,
                            snackName = "Coke",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 3,
                            SnackTypeId = 2,
                            snackCalories = 160,
                            snackName = "Lays Original",
                            snackPrice = 0.75,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 4,
                            SnackTypeId = 1,
                            snackCalories = 240,
                            snackName = "Iced Coffee",
                            snackPrice = 3.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 5,
                            SnackTypeId = 2,
                            snackCalories = 160,
                            snackName = "Lays BBQ",
                            snackPrice = 0.75,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 6,
                            SnackTypeId = 3,
                            snackCalories = 215,
                            snackName = "Snickers",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 7,
                            SnackTypeId = 1,
                            snackCalories = 150,
                            snackName = "Dr. Pepper",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 8,
                            SnackTypeId = 2,
                            snackCalories = 150,
                            snackName = "Doritos Salsa Verde",
                            snackPrice = 1.0,
                            vendingMachineId = 1
                        },
                        new
                        {
                            id = 9,
                            SnackTypeId = 1,
                            snackCalories = 168,
                            snackName = "Red Bull",
                            snackPrice = 2.5,
                            vendingMachineId = 2
                        });
                });

            modelBuilder.Entity("Nosh.Models.SnackType", b =>
                {
                    b.Property<int>("SnackTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Snackid");

                    b.Property<string>("imageURL");

                    b.Property<string>("snackTypeName");

                    b.HasKey("SnackTypeId");

                    b.HasIndex("Snackid");

                    b.ToTable("SnackType");

                    b.HasData(
                        new
                        {
                            SnackTypeId = 1,
                            imageURL = "/images/milk-bottle.png",
                            snackTypeName = "Drink"
                        },
                        new
                        {
                            SnackTypeId = 2,
                            imageURL = "/images/snack.png",
                            snackTypeName = "Chip"
                        },
                        new
                        {
                            SnackTypeId = 3,
                            imageURL = "/images/chocolate-bar.png",
                            snackTypeName = "Candy"
                        });
                });

            modelBuilder.Entity("Nosh.Models.UserSnack", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("snackId");

                    b.Property<int>("userId");

                    b.Property<string>("userId1");

                    b.HasKey("id");

                    b.HasIndex("snackId");

                    b.HasIndex("userId1");

                    b.ToTable("UserSnack");

                    b.HasData(
                        new
                        {
                            id = 1,
                            snackId = 8,
                            userId = 1
                        },
                        new
                        {
                            id = 2,
                            snackId = 7,
                            userId = 1
                        },
                        new
                        {
                            id = 3,
                            snackId = 9,
                            userId = 2
                        },
                        new
                        {
                            id = 4,
                            snackId = 1,
                            userId = 3
                        },
                        new
                        {
                            id = 5,
                            snackId = 7,
                            userId = 3
                        });
                });

            modelBuilder.Entity("Nosh.Models.VendingMachine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("vendingMachineLocation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("vendingMachineName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("VendingMachine");

                    b.HasData(
                        new
                        {
                            id = 2,
                            vendingMachineLocation = "Closest to the coffee pot",
                            vendingMachineName = "Loud and Cold"
                        },
                        new
                        {
                            id = 1,
                            vendingMachineLocation = "Across from the microwaves",
                            vendingMachineName = "The Mothership"
                        });
                });

            modelBuilder.Entity("Nosh.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("firstName")
                        .IsRequired();

                    b.Property<bool>("isVendor");

                    b.Property<string>("lastName")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "ec255e6d-84f2-422a-a483-b577cd2e8298",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44fbd1ff-2bdc-43a3-aafe-6ccb1453e9ec",
                            Email = "hmetts@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HMETTS@GMAIL.COM",
                            NormalizedUserName = "HMETTS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBiohN0v+yZ74JZe3YiqJyL1C3HSlyhbYJr7PCYzD5RGbmwkqYL907/Gwb1jrM/Lig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "814a78fc-de85-42e0-948a-d1eb078382fb",
                            TwoFactorEnabled = false,
                            UserName = "hmetts@gmail.com",
                            firstName = "Hunter",
                            isVendor = false,
                            lastName = "Metts"
                        },
                        new
                        {
                            Id = "5df331d2-d794-4370-a88f-ed2abe6e43fb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40872b0f-0a72-4711-ab97-d200f895a8f9",
                            Email = "jrosas@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JROSAS@GMAIL.COM",
                            NormalizedUserName = "JROSAS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELP1J4IOPA6RVt3c3Ov+tXJB/97cqvG2MJZTBcychUeIFpbxVIDXX9tvnK80oRybuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2efd3c4-c7ec-4abd-893b-db793279e58e",
                            TwoFactorEnabled = false,
                            UserName = "jrosas@gmail.com",
                            firstName = "Jordan",
                            isVendor = false,
                            lastName = "Rosas"
                        },
                        new
                        {
                            Id = "9d5ee710-a38a-4f9e-a9dd-4838705922a2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eab510da-877e-47f4-8e5c-8c9fbdf41948",
                            Email = "acarter@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACARTER@GMAIL.COM",
                            NormalizedUserName = "ACARTER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKimWlYPGZAXRHYo4HvlnI8LvFI1Bpw4oWIb2GfSijD2EbnPxxVEi5lbFQhDUzsx/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "647d88cc-cfb8-4721-80de-4099bccdb06c",
                            TwoFactorEnabled = false,
                            UserName = "acarter@gmail.com",
                            firstName = "Asia",
                            isVendor = false,
                            lastName = "Carter"
                        },
                        new
                        {
                            Id = "937e5e51-8e25-404a-b0e7-4b82170d7bc3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05b34245-8c90-4869-918c-fdfe9e58704f",
                            Email = "sbrader@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SBRADER@GMAIL.COM",
                            NormalizedUserName = "SBRADER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKBfCtj/yEEZGRZwq5kX+Dzj1XN4UeN7t1iqkClwNCevp5i25Ky1ghsAL2zK+imjqA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e55019f0-b1eb-4f09-9291-906a353db20e",
                            TwoFactorEnabled = false,
                            UserName = "sbrader@gmail.com",
                            firstName = "Steven",
                            isVendor = true,
                            lastName = "Brader"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Nosh.Models.Snack", b =>
                {
                    b.HasOne("Nosh.Models.SnackType", "snackType")
                        .WithMany()
                        .HasForeignKey("SnackTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nosh.Models.VendingMachine", "vendingMachine")
                        .WithMany("Snack")
                        .HasForeignKey("vendingMachineId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nosh.Models.SnackType", b =>
                {
                    b.HasOne("Nosh.Models.Snack")
                        .WithMany("SnackType")
                        .HasForeignKey("Snackid");
                });

            modelBuilder.Entity("Nosh.Models.UserSnack", b =>
                {
                    b.HasOne("Nosh.Models.Snack", "snack")
                        .WithMany("UserSnack")
                        .HasForeignKey("snackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nosh.Models.User", "user")
                        .WithMany("UserSnack")
                        .HasForeignKey("userId1");
                });
#pragma warning restore 612, 618
        }
    }
}
